[package]
name = "impg"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.0", features = ["derive"] }
#coitrees = { version = "0.4.0", features = ["nosimd"] }
coitrees = "0.4.0"
flate2 = "1.0.28"
